### PR TITLE
Add Nord flavor

### PR DESCRIPTION
**Pull request by tphecca**
[CSSDeck demo](http://cssdeck.com/labs/gtmjoor5)

Adapted from the [Nord color scheme](https://github.com/arcticicestudio/nord). 

There is a problem with the horizontal tables that I can't figure out, which causes cells to overlap each other. I changed nothing from the default flavor besides colors.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
Thank you very much for the contribution. I will add your flavor to the next release (**v2.1.1**) and try to figure out why horizontal tables behave like this in your flavor. If they do not behave properly, I might disable horizontal tables until the issue has been resolved and then enable them again in a later patch. Is that ok with you?

**Comment by Chalarangelo** [comment]
## Update

I did find the reason for this behavior. Turns out that the problem comes from an optimization in [line 33 of the table module](https://github.com/Chalarangelo/mini.css/blob/master/src/mini/_table.scss#L33), where the `background` is not set if the color used is the same as the one used in the body. However, this causes the cells to not update properly, meaning they end up overlapping as your flavor file showcased. This can be very easily resolved on my end by updating the file to remove the condition. So, your flavor will display horizontal tables properly. If you want to see it work, just add the following:

```css
table td {
  background: #ECEFF4;
}
```

I will merge the PR very soon and update the [`dev211`](https://github.com/Chalarangelo/mini.css/tree/dev211) branch on which I am working to deal with this bug and make your flavor shine.

### Releasing the flavor

I will move your demo to a codepen to keep with tradition (all the other demos are on codepen) and I will add a short description in the flavor file and the documentation pages. 
I am willing to actively maintain it myself in the future (meaning mainly adding new features and keeping it compatible with changes in the codebase), if you don't want to.
If that's the case, just say the word, otherwise keep [your fork](https://github.com/DivergentThinking/mini.css) alive, for me to open PRs before releases, so that you can update it.

**Comment by tphecca** [comment]
I am going to be using this flavor in one of my own projects, so I will try to pull changes and keep it up-to-date for the foreseeable future. Thanks!

**Comment by Chalarangelo** [comment]
Great! I already updated it to **v2.1.1** which will be releasing this weekend. The only changes I made were adding a couple of variables that were added in for the latest release and calling a couple of mixins that were recently added for responsive hiding. Feel free to update your fork as soon as the update is released, so that you are up-to-date. Estimated release date is April, 21st, but it might be a day earlier or a day later.

**Pull request merged**
