### PR TITLE
:bug: fix(table): Add <td> min-height

### LINKED ISSUE #101: Empty <td data-label="Test"></td> breaks table layout
I noticed that when the `<td>` is empty and we have specified a data-label then the table layout breaks at that point. In the attached screenshot the "td 3' is empty.
2017-10-15_14h21_24

### PR DESCRIPTION
**Pull request by anselal**
Fixes #101 
I applied the fix only to the _table.scss file. If the fix is correct you also need to recompile to css. Sorry but I am new to scss ;)

### CODE REVIEW

**Review by Chalarangelo — APPROVED** [review]
The fix is correct, however I need to make it modular and apply to all flavors. It will be merged soon, made customizable and applied to all flavors. Expect a hotfix in the next few hours.

**Comment by Chalarangelo** [comment]
I changed the branch to `fermion.v2`, as the `master` branch is now going to be housing both **Fermion** and **Gluon** in the docs and it might cause some confusion. All subsequent PRs and releases will be based on `fermion.v2`. 

Thanks you very much for the help @anselal, you are now part of the **mini.css** contributors club! 🎉

**Comment by anselal** [comment]
Thank you for giving me the opportunity to contribute. I have a lot to learn on SCSS and designing in general and I think I made a good start. I hope I will learn more so I can help this project grow.

**Comment by Chalarangelo** [comment]
**mini.css** is always looking for new contributors, so feel free to help with open issues or anything else. Reporting bugs and polishing features are just as important as writing the codebase in the first place. Community is everything! 😄

**Comment by anselal** [comment]
Will do my best to support your work !!! :smile:

**Pull request merged**
